### ISSUE TITLE
Cannot run a command from the internal image viewer

### ISSUE THREAD

**Issue by stilllman** [FelixBoers/sublime-external-tools#4]
Hello and thanks for your plugin!

Given a png file opened in sublime text with the internal image viewer, I would like to be able to run an external tool on this file from the command palette. When trying to do so, the console shows the following error:

`Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1456, in run_
    return self.run(**args)
  File "/Users/luc/Library/Application Support/Sublime Text 3/Installed Packages/ExternalTools.sublime-package/plugin.py", line 11, in run
  File "/Users/luc/Library/Application Support/Sublime Text 3/Installed Packages/ExternalTools.sublime-package/settings.py", line 17, in __init__
AttributeError: 'NoneType' object has no attribute 'settings'`

**Comment by FelixBoers** [comment]
Hi @stilllman. Thank you for your interest in this plugin. Unfortunately, I do have not much spare time to work on your issue. 

This is what I can tell:
It looks like an image buffer in Sublime Text is somehow different compared to a text buffer. 
The message states that the `view` has no `settings()` method (See [here](https://github.com/FelixBoers/sublime-external-tools/blob/39554daf8208ab1a8714cb97760dbde382a8be5f/settings.py#L17)).

It might be necessary to load the settings somehow differently.
But since I'm not even using Sublime Text anymore in my daily work, I fear your only chance is to dig into this by yourself and create a pull request (or find someone who will). Sorry :)
